# Generated by Django 5.2.6 on 2025-09-28 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='image',
        ),
        migrations.AddField(
            model_name='plant',
            name='image_url',
            field=models.URLField(default='https://via.placeholder.com/400x300.png?text=Plant'),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
