# Generated by Django 5.2.6 on 2025-09-28 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_plant_image_plant_image_url_delete_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='image_url',
        ),
        migrations.AddField(
            model_name='plant',
            name='image',
            field=models.ImageField(default='plants/default.png', upload_to='plants/'),
            preserve_default=False,
        ),
    ]
