# Generated by Django 5.2.6 on 2025-09-28 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_plant_image_url_plant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='image',
            field=models.ImageField(default='plants/default.png', upload_to='plants/'),
        ),
    ]
